version: "3.8"
services:
    postgres:
        image: postgres:16
        container_name: z_vp_db
        restart: always
        environment:
            POSTGRES_USER: ${DATABASE_USER}
            POSTGRES_DB: ${DATABASE_NAME}
            POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
        volumes:
            - bot_postgres_data:/var/lib/postgresql/data
        networks:
            - telegram-bot-network

    bot:
        container_name: z_vp_app
        build: .
        restart: always
        depends_on:
            postgres:
                condition: service_started
        env_file:
            - .env
        networks:
            - telegram-bot-network

volumes:
    bot_postgres_data:
networks:
    telegram-bot-network:
        driver: bridge
