version: "3.8"
services:
    postgres:
        image: postgres:16
        container_name: 3x-ui-bot-db
        restart: always
        environment:
            POSTGRES_USER: ${DATABASE_USER}
            POSTGRES_DB: ${DATABASE_NAME}
            POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
        ports:
            - "5434:5432"
        volumes:
            - bot_postgres_data:/var/lib/postgresql/data
        networks:
            - telegram-bot-network

volumes:
    bot_postgres_data:
networks:
    telegram-bot-network:
